version: 0.2

phases:
  install:
    commands:
      - sudo easy_install pip
      - sudo pip install mkdocs
      - sudo pip install awscli
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - aws s3 cp site s3://jared-has-a-cool-bucket-bro/ --recursive

artifacts:
  files:
    - site/**/*