version: 0.2

phases:
  install:
    commands:
      - sudo easy_install pip
      - sudo pip install mkdocs
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - ls -la

artifacts:
  files:
    - site/**/*